/**
 * Generated by create-x402-app.
 *
 * Buyer-agent demo. Calls the paid endpoint with `AgentWallet.paidCall(url)`,
 * which transparently handles the 402 → sign → retry loop.
 *
 * Required env:
 *   BUYER_PRIVATE_KEY — any test EOA private key (use viem.generatePrivateKey)
 *   SELLER_BASE       — defaults to http://127.0.0.1:3030
 */
import { AgentWallet, AgentWalletError } from "@picoflow/agent-wallet";

async function main() {
  const pk = process.env.BUYER_PRIVATE_KEY as `0x${string}` | undefined;
  if (!pk || !pk.startsWith("0x") || pk.length !== 66) {
    throw new Error(
      "BUYER_PRIVATE_KEY must be a 0x-prefixed 64-hex-character private key — generate one with `node -e \"console.log(require('viem/accounts').generatePrivateKey())\"`",
    );
  }
  const base = process.env.SELLER_BASE ?? "http://127.0.0.1:3030";
  const wallet = new AgentWallet({
    privateKey: pk,
    rpcUrl: process.env.ARC_RPC ?? "https://rpc.testnet.arc.network",
    verbose: true,
  });

  // eslint-disable-next-line no-console
  console.log(`[__APP_NAME__] buyer = ${wallet.address}`);

  for (const symbol of ["SOL", "ETH", "BTC"]) {
    try {
      const r = await wallet.paidCall<{ symbol: string; spot_usd: number }>(
        `${base}/api/quote/${symbol}`,
      );
      // eslint-disable-next-line no-console
      console.log(
        `  ${symbol}: $${r.data.spot_usd}  (status=${r.status}, latency=${r.totalLatencyMs}ms, paid=${r.payment ? "yes" : "no"})`,
      );
    } catch (err) {
      if (err instanceof AgentWalletError) {
        // eslint-disable-next-line no-console
        console.error(`  ${symbol}: ${err.code} — ${err.message}`);
      } else {
        // eslint-disable-next-line no-console
        console.error(`  ${symbol}: ${(err as Error).message}`);
      }
    }
  }
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});
