/**
 * Generated by create-x402-app.
 *
 * Minimal Express server that exposes one paid endpoint via x402:
 *
 *   GET /api/quote/:symbol  →  $0.001 USDC per call
 *
 * Flow:
 *   1. First request: server returns `402 Payment Required` + the EIP-712
 *      challenge.
 *   2. Buyer signs the challenge with their EOA and retries with the
 *      `X-PAYMENT` header.
 *   3. Server verifies the signature against EIP-3009 USDC on Arc Testnet
 *      and serves the real response.
 *
 * Settlement (actually moving USDC on-chain) is intentionally out of scope
 * for this template — it shows the *facilitator* loop. To settle, run the
 * PicoFlow GatewayWorker against the same Postgres or call
 * `transferWithAuthorization` directly with a relayer key.
 */
import express from "express";
import { isAddress } from "viem";
import {
  ARC_TESTNET,
  buildChallenge,
  decodePaymentHeader,
  verifyPayment,
  type SignedPayment,
} from "@picoflow/x402-facilitator";

const PORT = Number(process.env.PORT ?? 3030);
const SELLER_ADDR =
  (process.env.SELLER_ADDR as `0x${string}`) ??
  "0x000000000000000000000000000000000000abcd";

if (!isAddress(SELLER_ADDR)) {
  throw new Error(`SELLER_ADDR is not a valid EVM address: ${SELLER_ADDR}`);
}

const app = express();
app.use(express.json({ limit: "32kb" }));

const PRICE = "0.001"; // 0.001 USDC per call

// In-process nonce set so a signed authorization can only be redeemed once.
// Replace with a Postgres lookup (`SELECT 1 FROM payments WHERE nonce=$1`)
// for multi-instance deployments.
const seenNonces = new Set<string>();

app.get("/api/healthz", (_req, res) => res.json({ ok: true }));

app.get("/api/quote/:symbol", async (req, res) => {
  const headerVal = req.header("x-payment");
  const symbol = String(req.params.symbol).toUpperCase().slice(0, 12);

  if (!headerVal) {
    const challenge = buildChallenge({
      price: PRICE,
      to: SELLER_ADDR,
      asset: ARC_TESTNET.usdc,
      network: ARC_TESTNET.chainId,
      description: `Spot quote for ${symbol}`,
    });
    res.status(402).json(challenge);
    return;
  }

  let signed: SignedPayment;
  try {
    signed = decodePaymentHeader(headerVal) as SignedPayment;
  } catch {
    res.status(400).json({ error: "malformed X-PAYMENT header" });
    return;
  }

  const challenge = buildChallenge({
    price: PRICE,
    to: SELLER_ADDR,
    asset: ARC_TESTNET.usdc,
    network: ARC_TESTNET.chainId,
  });
  challenge.nonce = signed.nonce;
  challenge.validAfter = signed.validAfter;
  challenge.validBefore = signed.validBefore;

  try {
    await verifyPayment(challenge, signed, {
      isNonceFresh: async (nonce) => !seenNonces.has(nonce),
    });
  } catch (err) {
    res.status(402).json({ error: (err as Error).message });
    return;
  }
  seenNonces.add(signed.nonce);

  // ---- The actual paid work ----
  // (Replace with your real upstream call. For demo: deterministic synth.)
  const spot = 100 + (symbol.charCodeAt(0) % 50) + Math.random() * 0.5;
  res.json({
    symbol,
    spot_usd: Number(spot.toFixed(4)),
    ts: Date.now(),
    paid_by: signed.from,
    note: "settlement is deferred to the gateway-batch worker (or a relayer); this response confirms only that the buyer's signed authorization is valid",
  });
});

app.listen(PORT, () => {
  // eslint-disable-next-line no-console
  console.log(`[__APP_NAME__] paid API listening on http://127.0.0.1:${PORT}`);
  // eslint-disable-next-line no-console
  console.log(`  GET /api/quote/:symbol → $${PRICE} USDC per call`);
});
